services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Symfony\Component\DependencyInjection\ContainerInterface:
    # REGISTER USER COMMAND
    Iam\Application\Handlers\Command\RegisterCommandHandler:
        tags:
            - { name: 'messenger.message_handler', bus: 'messenger.bus.default', handles: 'Iam\Application\Handlers\Command\RegisterCommand' }